spring:
  jpa:
    database: H2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    #url = jdbc:h2:mem:dbc2m
    #url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    url: jdbc:h2:tcp://localhost:9091,localhost:9092/data
    username: sa
    password: 
    
 #在浏览器中开启控制台 localhost:2020/h2-console
#  h2:
#    console:
#      settings:
#        web-allow-others: true
#      path: /h2
#      enabled: true
