server:
  port: 8004
  servlet:
    context-path: /h2
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG
spring:
  jpa:
    show-sql: true
  messages:
    basename: i18n/messages, i18n/messages_zh
management:
  security:
    roles: ADMIN