server:
  port: 8003
  servlet:    context-path: /data
  

spring:
  application:    name: danyuan-serve-h2
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - h2  
    - hikari

app:
  name: ${spring.application.name}
  version: @project.version@
  