server:
  port: 8001  servlet:    context-path: /
spring:
  application:    name: danyuan-gateway
  banner:    charset: utf-8
  profiles:
    active:
    - gateway
    - nacos


app:
  name: ${spring.application.name}
  version: @project.version@