server:
  port: 8004
  servlet:    context-path: /database
  

spring:
  application:    name: danyuan-serve-mysql
  banner:    charset: utf-8
  profiles:
    active:
    - nacos
    - mysql
    - hikari

app:
  name: ${spring.application.name}
  version: @project.version@