logging:
  level:
    jdbc:
      resultsettable: DEBUG
      sqltiming: DEBUG

      

user:
  old-path: "C:\\Users\\Administrator\\Downloads\\user-2787821-1629783487\\user-2787821-1629783486"
  new-path: "D:\\git\\danyuan-tools-web\\docs\\docs2"
  img-path: "D:\\git\\danyuan-tools-web\\docs\\images2"
  root-path: "../../images"
  
        