spring:
  jpa:
    open-in-view: true
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    platform: H2
    driver-class-name: org.h2.Driver
    #url = jdbc:h2:mem:dbc2m
    #url: jdbc:h2:file:./dbh2/dbc2m;AUTO_SERVER=TRUE
    url: jdbc:h2:tcp://localhost:9091,localhost:9092/data
    username: sa
    password: 
    initialization-mode: ALWAYS
    #启动时需要初始化的建表语句
    schema: classpath:schema-h2.sql
    #初始化的数据
    data: classpath:data-h2.sql
    sql-script-encoding: utf-8
    separator: ;